### PR TITLE
Added Badges and Config-UI-X Link for easy setup.

### PR DESCRIPTION
**Pull request by donavanbecker**
I added NPM Version Badge and link, NPM Download Badge and link, Github Issues amount and link, Github Pull Request amount and link, and also added the config-ui-x easy install and setup into the Readme.

### CODE REVIEW

**Comment by donavanbecker** [comment]
If you would prefer not to have this that's fine, but think it easier for other noob users.

**Comment by lukasroegner** [comment]
@donavanbecker thank you! I like the additional installation instructions.
If you remove the badges (I don't see a benefit), I'll merge it to master.

**Comment by donavanbecker** [comment]
Okay @lukasroegner badges remove

**Comment by lukasroegner** [comment]
Manually added in latest release.

**Pull request closed without merging**
