### PR TITLE
switch `getService` function for hb2.0

### PR DESCRIPTION
**Pull request by bwp91**
this will still work with existing versions of homebridge

### CODE REVIEW

**Comment by bwp91** [comment]
@lukasroegner i cant seem to request you properly as a reviewer

**Comment by lukasroegner** [comment]
Thank you for the PR @bwp91 ! Is there a compatibility issue with old homebridge installations when using `getServiceById` instead of  `getServiceByUUIDAndSubType`?

**Comment by bwp91** [comment]
I can't speak for _very very_ old versions of homebridge, but for a long time these two have just been basically duplicate methods, same signature, same return values etc.

here is the link to the code in homebridge with these two methods:

https://github.com/homebridge/homebridge/blob/59e08934806b64a1a759f026b91244eb28c377de/src/platformAccessory.ts#L110-L122

**Comment by lukasroegner** [comment]
Yea, the deprecation comment has been added to `getServiceByUUIDAndSubType` 4 years ago, so I would say it's safe to switch to `getServiceById`.

Have you tested your branch on homebridge 2.0?

**Comment by bwp91** [comment]
I don't actually use this plugin, so locally I couldn't really check that my changes made any difference.

I don't know whether you could publish as a beta? So the users from here could try it?
https://github.com/lukasroegner/homebridge-dyson-pure-cool/issues/346

**Comment by lukasroegner** [comment]
I've checked the homebridge code, `getServiceByUUIDAndSubType` internally only calls `getServiceById`, so this should be safe.

**Pull request merged**
